### ISSUE TITLE
Unreviewed commit on master!

### ISSUE THREAD

**Issue by heimdall-asguard** [coinbase/rules_ruby#24]
Unreviewed commit(s) [COMPARE](https://github.com/coinbase/rules_ruby/compare/e23806201c909449b15489583a0fc14d164f6706...ad46a7c4a599d1470d38535d117429d469cc229b) was merged to master by grahamjenson.

Comment with appropriate number of :+1: to approve.

**Comment by heimdall-asguard** [comment]
Reviews      | 0/1
------------ | -------------




[More info](https://heimdall-public.cbhq.net/v1/code_change?repository=coinbase/rules_ruby&ref=ad46a7c4a599d1470d38535d117429d469cc229b)

**Comment by ClareCat** [comment]
👍

**Comment by heimdall-asguard** [comment]
Reviews      | 1/1
------------ | -------------
ClareCat | 1

Pull request is reviewed and can be merged to master!

[More info](https://heimdall-public.cbhq.net/v1/code_change?repository=coinbase/rules_ruby&ref=ad46a7c4a599d1470d38535d117429d469cc229b)
